<?php
// database/seeders/PageRelatedSeeders/PageSectionsSeeder.php
namespace Database\Seeders\PageRelatedSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PageSectionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        Schema::disableForeignKeyConstraints();

        // Truncate the table to avoid duplicate entries
        DB::table('page_sections')->truncate();

        // Insert all page sections for Home page (page_id = 1)
        DB::table('page_sections')->insert([

            // Home page sections
            [
                'id' => 1,
                'page_id' => 1,
                'section_key' => 'hero',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'page_id' => 1,
                'section_key' => 'services',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'page_id' => 1,
                'section_key' => 'features',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'page_id' => 1,
                'section_key' => 'howItWorks',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'page_id' => 1,
                'section_key' => 'industries',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'page_id' => 1,
                'section_key' => 'successStories',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'page_id' => 1,
                'section_key' => 'testimonials',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'page_id' => 1,
                'section_key' => 'pricingPlans',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'page_id' => 1,
                'section_key' => 'faq',
                'variant' => 'variant1',
                'order' => 9,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'page_id' => 1,
                'section_key' => 'contact',
                'variant' => 'variant1',
                'order' => 10,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'page_id' => 1,
                'section_key' => 'aboutUs',
                'variant' => 'variant1',
                'order' => 11,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'page_id' => 1,
                'section_key' => 'whyChooseUs',
                'variant' => 'variant1',
                'order' => 12,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'page_id' => 1,
                'section_key' => 'integrations',
                'variant' => 'variant1',
                'order' => 13,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'page_id' => 1,
                'section_key' => 'news',
                'variant' => 'variant1',
                'order' => 14,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'page_id' => 1,
                'section_key' => 'partner',
                'variant' => 'variant1',
                'order' => 15,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'page_id' => 1,
                'section_key' => 'globalPresence',
                'variant' => 'variant1',
                'order' => 16,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'page_id' => 1,
                'section_key' => 'career',
                'variant' => 'variant1',
                'order' => 17,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'page_id' => 1,
                'section_key' => 'trustSignal',
                'variant' => 'variant1',
                'order' => 18,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'page_id' => 1,
                'section_key' => 'newsletter',
                'variant' => 'variant1',
                'order' => 19,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'page_id' => 1,
                'section_key' => 'mobileApp',
                'variant' => 'variant1',
                'order' => 20,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'page_id' => 1,
                'section_key' => 'event',
                'variant' => 'variant1',
                'order' => 21,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'page_id' => 1,
                'section_key' => 'customSolutions',
                'variant' => 'variant1',
                'order' => 22,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'page_id' => 1,
                'section_key' => 'orderFulfillment',
                'variant' => 'variant1',
                'order' => 23,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'page_id' => 1,
                'section_key' => 'returnsManagement',
                'variant' => 'variant1',
                'order' => 24,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'page_id' => 1,
                'section_key' => 'supplyChainConsulting',
                'variant' => 'variant1',
                'order' => 25,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'page_id' => 1,
                'section_key' => 'transportationManagement',
                'variant' => 'variant1',
                'order' => 26,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'page_id' => 1,
                'section_key' => 'warehouseManagement',
                'variant' => 'variant1',
                'order' => 27,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Services Page Section
            [
                'id' => 28,
                'page_id' => 2,
                'section_key' => 'allServices',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'page_id' => 2,
                'section_key' => 'warehouseManagement',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'page_id' => 2,
                'section_key' => 'orderFulfillment',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'page_id' => 2,
                'section_key' => 'supplyChainConsulting',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'page_id' => 2,
                'section_key' => 'transportationManagement',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'page_id' => 2,
                'section_key' => 'returnManagement',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'page_id' => 2,
                'section_key' => 'customSolution',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Features Page Section
            [
                'id' => 35,
                'page_id' => 3,
                'section_key' => 'realTimeTracking',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'page_id' => 3,
                'section_key' => 'automatedReordering',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'page_id' => 3,
                'section_key' => 'multiWarehouseSupport',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'page_id' => 3,
                'section_key' => 'barcodeScanning',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'page_id' => 3,
                'section_key' => 'reportingAnalytics',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'page_id' => 3,
                'section_key' => 'integrationCapabilities',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'page_id' => 3,
                'section_key' => 'mobileAppFeatures',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'page_id' => 3,
                'section_key' => 'securityFeatures',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // How It Works Page Section's
            [
                'id' => 43,
                'page_id' => 4,
                'section_key' => 'stepByStepProcess',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'page_id' => 4,
                'section_key' => 'onboardingGuide',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'page_id' => 4,
                'section_key' => 'implementationTimeline',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'page_id' => 4,
                'section_key' => 'trainingAndSupport',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'page_id' => 4,
                'section_key' => 'successMetrics',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'page_id' => 4,
                'section_key' => 'caseStudies',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Industries Page Section's
            [
                'id' => 49,
                'page_id' => 5,
                'section_key' => 'eCommerceAndRetail',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'page_id' => 5,
                'section_key' => 'manufacturing',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'page_id' => 5,
                'section_key' => 'healthcareAndPharmaceuticals',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'page_id' => 5,
                'section_key' => 'foodAndBeverage',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'page_id' => 5,
                'section_key' => 'automotive',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'page_id' => 5,
                'section_key' => 'electronics',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'page_id' => 5,
                'section_key' => 'fashionAndApparel',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'page_id' => 5,
                'section_key' => 'wholesaleAndDistribution',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'page_id' => 5,
                'section_key' => 'thirdPartyLogistics',
                'variant' => 'variant1',
                'order' => 9,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'page_id' => 5,
                'section_key' => 'construction',
                'variant' => 'variant1',
                'order' => 10,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Re-enable foreign key checks
        Schema::enableForeignKeyConstraints();
    }
}
