<?php
// database/seeders/PageRelatedSeeders/PageSectionsSeeder.php
namespace Database\Seeders\PageRelatedSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PageSectionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        Schema::disableForeignKeyConstraints();

        // Truncate the table to avoid duplicate entries
        DB::table('page_sections')->truncate();

        // Insert all page sections for Home page (page_id = 1)
        DB::table('page_sections')->insert([
            $this->command->info('Starting Page Section Seeding... '),
            $this->command->info('Creating Home page sections...'),
            // Home page sections
            [
                'id' => 1,
                'page_id' => 1,
                'section_key' => 'hero',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'page_id' => 1,
                'section_key' => 'services',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'page_id' => 1,
                'section_key' => 'features',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'page_id' => 1,
                'section_key' => 'howItWorks',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'page_id' => 1,
                'section_key' => 'industries',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'page_id' => 1,
                'section_key' => 'successStories',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'page_id' => 1,
                'section_key' => 'testimonials',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'page_id' => 1,
                'section_key' => 'pricingPlans',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'page_id' => 1,
                'section_key' => 'faq',
                'variant' => 'variant1',
                'order' => 9,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'page_id' => 1,
                'section_key' => 'contact',
                'variant' => 'variant1',
                'order' => 10,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'page_id' => 1,
                'section_key' => 'aboutUs',
                'variant' => 'variant1',
                'order' => 11,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'page_id' => 1,
                'section_key' => 'whyChooseUs',
                'variant' => 'variant1',
                'order' => 12,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'page_id' => 1,
                'section_key' => 'integrations',
                'variant' => 'variant1',
                'order' => 13,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'page_id' => 1,
                'section_key' => 'news',
                'variant' => 'variant1',
                'order' => 14,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'page_id' => 1,
                'section_key' => 'partner',
                'variant' => 'variant1',
                'order' => 15,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'page_id' => 1,
                'section_key' => 'globalPresence',
                'variant' => 'variant1',
                'order' => 16,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'page_id' => 1,
                'section_key' => 'career',
                'variant' => 'variant1',
                'order' => 17,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'page_id' => 1,
                'section_key' => 'trustSignal',
                'variant' => 'variant1',
                'order' => 18,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'page_id' => 1,
                'section_key' => 'newsletter',
                'variant' => 'variant1',
                'order' => 19,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'page_id' => 1,
                'section_key' => 'mobileApp',
                'variant' => 'variant1',
                'order' => 20,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'page_id' => 1,
                'section_key' => 'event',
                'variant' => 'variant1',
                'order' => 21,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'page_id' => 1,
                'section_key' => 'customSolutions',
                'variant' => 'variant1',
                'order' => 22,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'page_id' => 1,
                'section_key' => 'orderFulfillment',
                'variant' => 'variant1',
                'order' => 23,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'page_id' => 1,
                'section_key' => 'returnsManagement',
                'variant' => 'variant1',
                'order' => 24,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'page_id' => 1,
                'section_key' => 'supplyChainConsulting',
                'variant' => 'variant1',
                'order' => 25,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'page_id' => 1,
                'section_key' => 'transportationManagement',
                'variant' => 'variant1',
                'order' => 26,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'page_id' => 1,
                'section_key' => 'warehouseManagement',
                'variant' => 'variant1',
                'order' => 27,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Home page sections...'),

            $this->command->info('Started Services page sections...'),
            // Services Page Section
            [
                'id' => 28,
                'page_id' => 2,
                'section_key' => 'allServices',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'page_id' => 2,
                'section_key' => 'warehouseManagement',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'page_id' => 2,
                'section_key' => 'orderFulfillment',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'page_id' => 2,
                'section_key' => 'supplyChainConsulting',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'page_id' => 2,
                'section_key' => 'transportationManagement',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'page_id' => 2,
                'section_key' => 'returnManagement',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'page_id' => 2,
                'section_key' => 'customSolution',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Services page sections...'),

            $this->command->info('Started Features page sections...'),
            // Features Page Section
            [
                'id' => 35,
                'page_id' => 3,
                'section_key' => 'realTimeTracking',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'page_id' => 3,
                'section_key' => 'automatedReordering',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'page_id' => 3,
                'section_key' => 'multiWarehouseSupport',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'page_id' => 3,
                'section_key' => 'barcodeScanning',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'page_id' => 3,
                'section_key' => 'reportingAnalytics',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'page_id' => 3,
                'section_key' => 'integrationCapabilities',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'page_id' => 3,
                'section_key' => 'mobileAppFeatures',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'page_id' => 3,
                'section_key' => 'securityFeatures',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Features page sections...'),

            $this->command->info('Started How It Works page sections...'),
            // How It Works Page Section's
            [
                'id' => 43,
                'page_id' => 4,
                'section_key' => 'stepByStepProcess',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'page_id' => 4,
                'section_key' => 'onboardingGuide',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'page_id' => 4,
                'section_key' => 'implementationTimeline',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'page_id' => 4,
                'section_key' => 'trainingAndSupport',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'page_id' => 4,
                'section_key' => 'successMetrics',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'page_id' => 4,
                'section_key' => 'caseStudies',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed How It Works page sections...'),

            $this->command->info('Started Industries page sections...'),
            // Industries Page Section's
            [
                'id' => 49,
                'page_id' => 5,
                'section_key' => 'eCommerceAndRetail',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'page_id' => 5,
                'section_key' => 'manufacturing',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'page_id' => 5,
                'section_key' => 'healthcareAndPharmaceuticals',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'page_id' => 5,
                'section_key' => 'foodAndBeverage',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'page_id' => 5,
                'section_key' => 'automotive',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'page_id' => 5,
                'section_key' => 'electronics',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'page_id' => 5,
                'section_key' => 'fashionAndApparel',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'page_id' => 5,
                'section_key' => 'wholesaleAndDistribution',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'page_id' => 5,
                'section_key' => 'thirdPartyLogistics',
                'variant' => 'variant1',
                'order' => 9,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'page_id' => 5,
                'section_key' => 'construction',
                'variant' => 'variant1',
                'order' => 10,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Industries page sections...'),

            $this->command->info('Starting Success Stories page sections...'),
            // Success Stories page sections
            [
                'id' => 59,
                'page_id' => 6,
                'section_key' => 'clientSuccessMetrics',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'page_id' => 6,
                'section_key' => 'beforeAfterScenarios',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'page_id' => 6,
                'section_key' => 'roiCalculations',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'page_id' => 6,
                'section_key' => 'industrySpecificExamples',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Success Stories page sections...'),

            $this->command->info('Starting Testimonials page sections...'),
            // Testimonials page sections
            [
                'id' => 63,
                'page_id' => 7,
                'section_key' => 'customerReviews',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'page_id' => 7,
                'section_key' => 'videoTestimonials',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'page_id' => 7,
                'section_key' => 'writtenTestimonials',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'page_id' => 7,
                'section_key' => 'industryExpertReviews',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'page_id' => 7,
                'section_key' => 'partnerTestimonials',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'page_id' => 7,
                'section_key' => 'ratingAndAwards',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Testimonials page sections...'),

            $this->command->info('Starting Pricing Plans page sections...'),
            // Pricing Plans page sections
            [
                'id' => 69,
                'page_id' => 8,
                'section_key' => 'starterPlan',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'page_id' => 8,
                'section_key' => 'professionalPlan',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'page_id' => 8,
                'section_key' => 'enterprisePlan',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'page_id' => 8,
                'section_key' => 'CustomPricing',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'page_id' => 8,
                'section_key' => 'freeTrial',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'page_id' => 8,
                'section_key' => 'featureComparisonTable',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'page_id' => 8,
                'section_key' => 'faqAboutPricing',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Pricing Plans page sections...'),

            $this->command->info('Starting FAQ page sections...'),
            // FAQ page sections
            [
                'id' => 76,
                'page_id' => 9,
                'section_key' => 'generalQuestions',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'page_id' => 9,
                'section_key' => 'billingPricing',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'page_id' => 9,
                'section_key' => 'technicalSupport',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'page_id' => 9,
                'section_key' => 'implementation',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'page_id' => 9,
                'section_key' => 'integrationsFAQ',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'page_id' => 9,
                'section_key' => 'dataSecurity',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'page_id' => 9,
                'section_key' => 'accountManagement',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed FAQ page sections...'),

            $this->command->info('Starting Contact page sections...'),
            // Contact page sections
            [
                'id' => 83,
                'page_id' => 10,
                'section_key' => 'contactForm',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'page_id' => 10,
                'section_key' => 'salesInquiries',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'page_id' => 10,
                'section_key' => 'supportRequests',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'page_id' => 10,
                'section_key' => 'partnerInquiries',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'page_id' => 10,
                'section_key' => 'officeLocations',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'page_id' => 10,
                'section_key' => 'phoneNumbers',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'page_id' => 10,
                'section_key' => 'emailAddresses',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'page_id' => 10,
                'section_key' => 'liveChatOption',
                'variant' => 'variant1',
                'order' => 8,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Contact page sections...'),

            $this->command->info('Starting About Us page sections...'),
            // About Us Page Sections
            [
                'id' => 91,
                'page_id' => 11,
                'section_key' => 'companyStory',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'page_id' => 11,
                'section_key' => 'missionVision',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'page_id' => 11,
                'section_key' => 'coreValues',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'page_id' => 11,
                'section_key' => 'leadershipTeam',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'page_id' => 11,
                'section_key' => 'companyTimeline',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'page_id' => 11,
                'section_key' => 'cultureCareers',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'page_id' => 11,
                'section_key' => 'awardsRecognition',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed About Us page sections...'),

            $this->command->info('Starting Why Choose Us page sections...'),
            // Why Choose Us Page Sections
            [
                'id' => 98,
                'page_id' => 12,
                'section_key' => 'competitiveAdvantages',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'page_id' => 12,
                'section_key' => 'uniqueSellingPoints',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'page_id' => 12,
                'section_key' => 'customerSatisfactionStats',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'page_id' => 12,
                'section_key' => 'industryExpertise',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'page_id' => 12,
                'section_key' => 'technologyInnovation',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'page_id' => 12,
                'section_key' => 'support24x7',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'page_id' => 12,
                'section_key' => 'globalReach',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Why Choose Us page sections...'),

            $this->command->info('Starting Blog page sections...'),
            // Blog Page Sections
            [
                'id' => 105,
                'page_id' => 13,
                'section_key' => 'industryInsights',
                'variant' => 'variant1',
                'order' => 1,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'page_id' => 13,
                'section_key' => 'productUpdates',
                'variant' => 'variant1',
                'order' => 2,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'page_id' => 13,
                'section_key' => 'howToGuides',
                'variant' => 'variant1',
                'order' => 3,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'page_id' => 13,
                'section_key' => 'bestPractices',
                'variant' => 'variant1',
                'order' => 4,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'page_id' => 13,
                'section_key' => 'companyNews',
                'variant' => 'variant1',
                'order' => 5,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'page_id' => 13,
                'section_key' => 'expertArticles',
                'variant' => 'variant1',
                'order' => 6,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'page_id' => 13,
                'section_key' => 'videoContent',
                'variant' => 'variant1',
                'order' => 7,
                'enabled' => 1,
                'props' => json_encode([]),
                'device' => null,
                'locale' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $this->command->info('Completed Blog page sections...'),

            
        ]);

        // Re-enable foreign key checks
        Schema::enableForeignKeyConstraints();
    }
}
