// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/**/*.{js,ts,jsx,tsx}',
        './resources/**/*.{js,ts,jsx,tsx,blade.php}',
    ],
    theme: {
        extend: {},
    },
    safelist: [
        // Widths
        'w-full',
        'w-screen',
        'w-auto',
        'min-w-full',
        'min-w-0',
        'max-w-none',
        'max-w-sm',
        'max-w-md',
        'max-w-lg',
        'max-w-xl',
        'max-w-2xl',
        'max-w-3xl',
        'max-w-4xl',
        'max-w-5xl',
        'max-w-6xl',
        'max-w-7xl',

        // Heights
        'h-full',
        'h-screen',
        'h-auto',
        'h-min',
        'h-max',
        'min-h-screen',
        'max-h-screen',

        // Spacing (common)
        'p-0',
        'p-1',
        'p-2',
        'p-3',
        'p-4',
        'p-5',
        'p-6',
        'p-8',
        'p-10',
        'p-12',
        'p-16',
        'px-0',
        'px-1',
        'px-2',
        'px-4',
        'px-6',
        'px-8',
        'py-0',
        'py-1',
        'py-2',
        'py-4',
        'py-6',
        'py-8',
        'py-12',
        'py-16',
        'm-0',
        'm-1',
        'm-2',
        'm-3',
        'm-4',
        'm-5',
        'm-6',
        'mx-auto',

        // Grid & flex
        'grid',
        'flex',
        'inline-flex',
        'inline-block',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'grid-cols-5',
        'grid-cols-6',
        'grid-cols-12',
        'gap-0',
        'gap-1',
        'gap-2',
        'gap-4',
        'gap-6',
        'gap-8',
        'justify-start',
        'justify-center',
        'justify-end',
        'justify-between',
        'justify-around',
        'justify-evenly',
        'items-start',
        'items-center',
        'items-end',
        'items-stretch',

        // Borders & rounding
        'border',
        'border-t',
        'border-b',
        'border-l',
        'border-r',
        'border-gray-200',
        'rounded',
        'rounded-lg',
        'rounded-full',
        'rounded-t',
        'rounded-b',

        // Shadows
        'shadow',
        'shadow-md',
        'shadow-lg',
        'hover:shadow-lg',
        'transition-shadow',

        // Backgrounds
        'bg-white',
        'bg-gray-100',
        'bg-gray-200',
        'bg-gray-300',
        'bg-black',
        'bg-blue-900',
        'bg-blue-800',
        'dark:bg-gray-900',
        'bg-linear-to-r',
        'bg-linear-to-br',
        'from-blue-900',
        'via-blue-800',
        'to-blue-900',
        {
            pattern: /bg-linear-to-(t|tr|r|br|b|bl|l|tl)/,
        },
        {
            pattern: /(from|via|to)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)/,
        },
        {
            pattern: /(text|bg|border)-\[#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\]/,
        },
        {
            pattern: /(text|bg|border)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)/,
        },
        {
            pattern: /text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl)/,
        },
        {
            pattern: /font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black)/,
        },
        {
            pattern: /(p|px|py|pt|pr|pb|pl|m|mx|my|mt|mr|mb|ml)-([0-9]|0\.5|1\.5|2\.5|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96)/,
        },
        {
            pattern: /leading-(none|tight|snug|normal|relaxed|loose|3|4|5|6|7|8|9|10)/,
        },
        {
            pattern: /tracking-(tighter|tight|normal|wide|wider|widest)/,
        },
        {
            pattern: /rounded-(none|sm|md|lg|xl|2xl|3xl|full)/,
        },
        {
            pattern: /shadow-(sm|md|lg|xl|2xl|inner|none)/,
        },

        // Opacity
        'opacity-0',
        'opacity-25',
        'opacity-50',
        'opacity-75',
        'opacity-100',

        // Responsive prefixes
        'sm:grid-cols-1',
        'sm:gap-4',
        'md:grid-cols-2',
        'md:gap-6',
        'lg:grid-cols-3',
        'lg:gap-8',
    ],
};
